
[functions.cleanup-old-events]
enabled = true
verify_jwt = true
import_map = "./functions/cleanup-old-events/deno.json"
entrypoint = "./functions/cleanup-old-events/index.ts"

[functions.cleanup-old-images]
enabled = true
verify_jwt = true
import_map = "./functions/cleanup-old-images/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cleanup-old-images/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cleanup-old-images/*.html" ]
